// import Navbar from './navbar'
import styles from "../../styles/Home.module.scss";
import Footer from './footer'
import Head from "next/head";
import Sidebar from "./sidebar";
import Topbar from "./Topbar";

export default function Layout({children}) {
    return (
        <>
            <div className={styles.layout_wrapper}>
                <Head>
                    <title>Dashboard Next</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                <Sidebar/>
                <main className={styles.main}>
                    <Topbar/>
                    {children}
                </main>
            </div>
        </>
    )
}